[tool.djlint]
profile="jinja"
linter_output_format = "{filename}:{line}: {code} {message} {match}"
# Ignore linting rules that are related to web pages
ignore = "H016,H021,H030,H031"

[tool.ruff]
extend-exclude = ["data", "models", "db", "cache"]

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I", "T10", "CPY"]
